"""Cut the dragon views out of the character sheet and build the recolour mask.

Usage: python tools/extract_character.py <character-sheet.png>
Writes assets/character/{back,front}.png (RGBA cut-outs) and
assets/character/{back,front}_mask.png (R = body/horns/wings, G = belly, B = keep as-is).
Needs pillow, numpy and scipy (build-time only; the game itself has no dependencies).
"""
import sys, colorsys
import numpy as np
from PIL import Image, ImageFilter
from scipy import ndimage

SHEET = sys.argv[1]
OUT = 'assets/character/'
# (left, top, right, bottom) of each view on the 1536x1024 sheet
VIEWS = {
    'front': (4, 52, 252, 408),
    'back': (668, 52, 892, 408),
}
# eye search areas on the trimmed front cut-out: (cx, cy, rx, ry)
EYES = {'front': [(68, 107, 27, 28), (151, 107, 27, 28)]}

def hsv(a):
    a = a.astype(np.float32) / 255
    r, g, b = a[..., 0], a[..., 1], a[..., 2]
    mx, mn = a.max(-1), a.min(-1)
    d = mx - mn + 1e-6
    h = np.where(mx == r, ((g - b) / d) % 6, np.where(mx == g, (b - r) / d + 2, (r - g) / d + 4)) * 60
    s = np.where(mx > 0, (mx - mn) / (mx + 1e-6), 0)
    return h, s, mx

sheet = Image.open(SHEET).convert('RGB')
for name, box in VIEWS.items():
    img = np.array(sheet.crop(box))
    h, s, v = hsv(img)
    # The background is a dark, nearly neutral grey. Compare against its colour (sampled
    # from the crop border) so shadowed parts of the character (lower belly, inner legs)
    # stay in even when they are dark.
    border = np.concatenate([img[:4].reshape(-1, 3), img[-4:].reshape(-1, 3), img[:, :4].reshape(-1, 3), img[:, -4:].reshape(-1, 3)]).astype(np.float32)
    bgc = np.median(border, 0)
    dist = np.sqrt(((img.astype(np.float32) - bgc) ** 2).sum(-1))
    fg = (dist > 46) & (((s > 0.38) & (v > 0.2)) | (v > 0.5))
    fg = ndimage.binary_opening(fg, iterations=1)
    lab, n = ndimage.label(fg)
    sizes = ndimage.sum(fg, lab, range(1, n + 1))
    keep = 1 + int(np.argmax(sizes))
    mask = ndimage.binary_fill_holes(lab == keep)
    mask = ndimage.binary_closing(mask, iterations=2)
    mask = ndimage.binary_fill_holes(mask)
    # soft edge: slightly eroded mask blurred for anti-aliasing
    alpha = Image.fromarray((ndimage.binary_erosion(mask, iterations=1) * 255).astype(np.uint8)).filter(ImageFilter.GaussianBlur(0.9))
    a = np.array(alpha)
    ys, xs = np.nonzero(a > 8)
    y0, y1, x0, x1 = max(0, ys.min() - 2), ys.max() + 3, max(0, xs.min() - 2), xs.max() + 3
    rgba = np.dstack([img, a])[y0:y1, x0:x1]
    Image.fromarray(rgba, 'RGBA').save(OUT + name + '.png', optimize=True)

    # recolour classes
    hh, ss, vv = h[y0:y1, x0:x1], s[y0:y1, x0:x1], v[y0:y1, x0:x1]
    belly = (hh > 54) & (hh < 150) & (ss > 0.3)
    belly = ndimage.binary_fill_holes(ndimage.binary_closing(ndimage.binary_opening(belly, iterations=1), iterations=2))
    keepm = np.zeros_like(belly)
    yy, xx = np.mgrid[0:rgba.shape[0], 0:rgba.shape[1]]
    skin = (hh > 33) & (hh < 54) & (ss > 0.55) & (vv > 0.5)
    for cx, cy, rx, ry in EYES.get(name, []):
        inside = ((xx - cx) / rx) ** 2 + ((yy - cy) / ry) ** 2 <= 1
        eye = ndimage.binary_fill_holes(inside & ~skin)
        lab, n = ndimage.label(eye)
        if n:
            eye = lab == 1 + int(np.argmax(ndimage.sum(eye, lab, range(1, n + 1))))
        keepm |= ndimage.binary_fill_holes(eye)
    belly &= ~keepm
    body = ~belly & ~keepm
    m = np.dstack([body * 255, belly * 255, keepm * 255]).astype(np.uint8)
    Image.fromarray(m, 'RGB').filter(ImageFilter.GaussianBlur(0.6)).save(OUT + name + '_mask.png', optimize=True)
    print(name, rgba.shape, 'belly px', int(belly.sum()), 'keep px', int(keepm.sum()))

# Embed the cut-outs as data URIs so the game also works from file:// (images loaded
# from files taint the canvas there, which blocks recolouring and the share card).
import base64
with open('js/render/character-data.js', 'w') as f:
    f.write('/* EGG RUN — generated by tools/extract_character.py, do not edit. */\n')
    f.write('(function (ER) {\n  ER.CHARACTER_DATA = {\n')
    for n in ['back', 'front', 'back_mask', 'front_mask']:
        b64 = base64.b64encode(open(OUT + n + '.png', 'rb').read()).decode()
        f.write("    %s: 'data:image/png;base64,%s',\n" % (n, b64))
    f.write('  };\n})(window.ER = window.ER || {});\n')
print('wrote js/render/character-data.js')
